mqtt {
    property_size = 32
    max_packet_size = 256MB
}

listeners.tcp {
    bind = "0.0.0.0:1883"
}

log {
    to = [console]
    level = info
}

rules {
    rule1 {
        sql = "SELECT * FROM \"sensor/#\""
        actions = [
            {
                name = "taos_sink"
                host = "127.0.0.1"
                port = 6041
                username = "root"
                password = "taosdata"
                database = "mqtt_rule"
                table = "mqtt_data"
            }
        ]
    }
}
