mqtt {
    property_size = 32
    max_packet_size = 256MB
}

listeners.tcp {
    bind = "0.0.0.0:1883"
}

log {
    to = [console]
    level = info
}

http_server {
    enable = true
    port = 8083
}

auth {
    allow_anonymous = true
}

rules.taos = [
    {
        conn = {
            host = "127.0.0.1"
            port = 6041
            username = "root"
            password = "taosdata"
            database = "mqtt_rule"
        }
        rules = [
            {
                sql = "SELECT * FROM \"weld/+/+/+/+/+/telemetry/env/#\""
                table = "weld_env_point"
                parser = "weld_telemetry"
            },
            {
                sql = "SELECT * FROM \"weld/+/+/+/+/+/telemetry/flow/#\""
                table = "weld_flow_point"
                parser = "weld_telemetry"
            },
            {
                sql = "SELECT * FROM \"weld/+/+/+/+/+/telemetry/power/#\" WHERE payload.signal_type = 'current'"
                table = "weld_current_point"
                parser = "weld_telemetry"
            },
            {
                sql = "SELECT * FROM \"weld/+/+/+/+/+/telemetry/power/#\" WHERE payload.signal_type = 'voltage'"
                table = "weld_voltage_point"
                parser = "weld_telemetry"
            }
        ]
    }
]
